### ISSUE TITLE
Error with file paths as arguments

### ISSUE THREAD

**Issue by michaeldzjap** [EdwardIrby/jsontosass-loader#8]
When I put this in my json:

```
{
  "background-url": "'some/image.jpg'"
}
```

I get the following error:
`Invalid CSS after "...background-url:": expected expression (e.g. 1px, bold), was "some/image.jp"`

**Comment by EdwardIrby** [comment]
So I'm not sure what you're doing but I don't believe there is a property called background-url. I know you can use background or background-image. So you're object should look like this.

``` js
{
  "background": "transparent url(some/image.jpg)"
}

// Where transparent is the background color and the url is the image in shorthand.
// or you can just do   

{
  "background-image": "url(some/image.jpg)"
}
```

**Comment by michaeldzjap** [comment]
Yes, sorry! This was a stupid mistake from my side.
